GROUP=com.shellaia.todero
POM_ARTIFACT_ID=todero-v3-ffi-android
POM_NAME=Todero V3 FFI Android
POM_DESCRIPTION=Android AAR packaging of the Todero V3 native runtime.
POM_URL=https://github.com/shellaia/todero-protocol-native
POM_LICENSE_NAME=Apache-2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_SCM_URL=https://github.com/shellaia/todero-protocol-native
POM_SCM_CONNECTION=scm:git:https://github.com/shellaia/todero-protocol-native.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/shellaia/todero-protocol-native.git
POM_DEVELOPER_ID=shellaia
POM_DEVELOPER_NAME=Shellaia
POM_DEVELOPER_URL=https://github.com/shellaia
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
