name: CI

on:
  workflow_dispatch:
#on:
#  push:
#    branches: ["**"]
#  pull_request:

jobs:
  rust-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Lint (clippy)
        run: cargo clippy --all-targets

      - name: Run tests
        run: cargo test --workspace

      - name: Release-check FFI crate
        run: cargo check -p v3-ffi --release
